# Generated by Django 4.2.30 on 2026-05-16 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransitionRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('notify_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transition_rules', to='db.state')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transition_rules', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'State Transition Rule',
                'verbose_name_plural': 'State Transition Rules',
                'db_table': 'state_transition_rules',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueWorkflowMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role_type', models.CharField(choices=[('approver', 'Approver'), ('co_worker', 'Co-worker')], max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_members', to='db.issue')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_workflow_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Workflow Member',
                'verbose_name_plural': 'Issue Workflow Members',
                'db_table': 'issue_workflow_members',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IssueApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('response_message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issue_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_from', to='db.state')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_issue_approvals', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_issue_approvals', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='db.statetransitionrule')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests_to', to='db.state')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Approval Request',
                'verbose_name_plural': 'Issue Approval Requests',
                'db_table': 'issue_approval_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='statetransitionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'from_state', 'to_state'), name='state_transition_rule_unique_active_transition'),
        ),
        migrations.AddConstraint(
            model_name='statetransitionrule',
            constraint=models.CheckConstraint(check=models.Q(('from_state', models.F('to_state')), _negated=True), name='state_transition_rule_distinct_states'),
        ),
        migrations.AddConstraint(
            model_name='issueworkflowmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'member', 'role_type'), name='issue_workflow_member_unique_active_role'),
        ),
        migrations.AddConstraint(
            model_name='issueworkflowmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('role_type', 'approver')), fields=('issue',), name='issue_workflow_member_single_active_approver'),
        ),
        migrations.AddConstraint(
            model_name='issueapprovalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'pending')), fields=('issue', 'from_state', 'to_state'), name='issue_approval_request_unique_pending_transition'),
        ),
    ]
