# Generated by Codex on 2026-05-17

from django.db import migrations, models


def seed_default_allowed_roles(apps, schema_editor):
    StateTransitionRule = apps.get_model("db", "StateTransitionRule")
    StateTransitionRule.objects.filter(allowed_roles=[]).update(allowed_roles=["approver"])


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_workflow_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="statetransitionrule",
            name="allowed_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(seed_default_allowed_roles, migrations.RunPython.noop),
    ]
