# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_state_transition_rule_allowed_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="workflow_roles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
